### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by onlyjob** [gogo/protobuf#101]
Tags/releases are useful as they allow package maintainers to track updates and export released versions as tarballs. Please consider tagging/releasing. Thanks.

**Comment by awalterschulze** [comment]
It just seems like extra work.
I have very rarely broken backwards compatibility and that was only because it was completely necessary.
Also github.com/golang/protobuf does not tag releases.

You have quite a few options to do this on your own though.
We git subtree all our dependencies.
When we have subtrees that depend on other subtrees for build jobs we use git-anchor
https://github.com/awalterschulze/git-anchor

But there are many other go vendoring options, including the go1.5 vendor experiment.

Another option is to fork this project and make your own release for private use.

I hope this helps?

**Comment by onlyjob** [comment]
No, this does not help. Tagging is not that hard. You can tag when significant changes are accumulated. I should file a similar bug to github.com/golang/protobuf -- anyway the fact that they do not follow best practice does not mean that you should do the same. Tagging would be helpful for Debian and (indirectly) for its derivatives. We do not want/need to fork this repository merely to apply non authoritative tags. Thanks.

**Comment by awalterschulze** [comment]
Ok I looked at a few go projects with the most stars.  It seems those popular non google projects do make releases.  This is new information to me.

I did not say it was hard, I said it was extra work.
When there is a small fix, there will need to be another small release.

Could you explain to me how this would help debian?

Does debian use  / want to use gogoprotobuf or only package it for others?

What does debian do with projects that do not follow best practices?

**Comment by onlyjob** [comment]
> Could you explain to me how this would help debian?

From maintainer prospective, it is quite useful when maintainer(s) notified about new releases of the upstream software. We have automated tools checking for new releases and special per-package "watch" files describing how to do that.

> Does debian use / want to use gogoprotobuf or only package it for others?

"gogoprotobuf" is a dependency for number of other projects/packages like "etcd" and others. Debian is highly modular and we use separate packages for every Go component. We do not just package for "others" although everyone is welcome to leverage our work. ;)

> What does debian do with projects that do not follow best practices?

Filing a bug?  ;)  Usually we are trying to communicate our concerns. Read more in [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide).

Thank you.

**Comment by awalterschulze** [comment]
Does this work for you?
https://github.com/gogo/protobuf/releases/tag/v0.1

**Comment by onlyjob** [comment]
Perfect, thank you. :)
