### ISSUE TITLE
godep issue

### ISSUE THREAD

**Issue by Quentin-M** [gogo/protobuf#111]
Hi,

As the [Godep's README](https://github.com/tools/godep/blob/master/Readme.md) says: 
```
Godep does not copy:
- files from source repositories that are not tracked in version control.
- _test.go files.
- testdata directories.
```

However, `proto/proto3_proto/proto3.pb.go`, which is not named as a test file, imports `proto/testdata`. Thus, any go app that relies on protobuf or that has a dependency using protobuf could vendor its deps using godep. Some other vendoring tools don't include test files by default either.

A simple work-around would be to use `godep save -t ./...` to vendor test files as well but I believe that it is not the right approach.

**Comment by awalterschulze** [comment]
This is a fork of golang/protobuf and this issue seems to be there as well.
Maybe you could first report the issue there and see what happens.
https://github.com/golang/protobuf/blob/master/proto/proto3_proto/proto3.proto
I will most probably merge any change they make.

If they refuse, I will have my own think about it.

**Comment by Quentin-M** [comment]
Awesome, thanks!
I did not notice that the issue was there as well.

**Comment by awalterschulze** [comment]
Can I close this?

**Comment by Quentin-M** [comment]
Go for it :)
