### ISSUE TITLE
proto3: cannot use `google.protobuf.Timestamp` from a message that uses Marshaller 

### ISSUE THREAD

**Issue by mwitkow** [gogo/protobuf#113]
I get:

```
stuff.pb.go:156: this.Creation.Equal undefined (type *google_protobuf.Timestamp has no field or method Equal)
stuff.pb.go:564: m.Creation.Size undefined (type *google_protobuf.Timestamp has no field or method Size)
stuff.pb.go:565: m.Creation.MarshalTo undefined (type *google_protobuf.Timestamp has no field or method MarshalTo)
stuff.pb.go:653: m.Creation.Size undefined (type *google_protobuf.Timestamp has no field or method Size)
stuff.pb.go:984: m.Creation.Unmarshal undefined (type *google_protobuf.Timestamp has no field or method Unmarshal)
```

on a proto when using GoGo Slick:
```proto
message Stuff {
  string name = 1;
  google.protobuf.Timestamp creation = 2;
```

This seems to be caused by the `vanity/files.go` `NotInPackageGoogleProtobuf` function, that ignores not only the `descriptor.proto` but also the other things.

Our (fairly complex) project cleanly compiles after a change to `NotInPackageGoogleProtobuf`:
```go
func NotInPackageGoogleProtobuf(file *descriptor.FileDescriptorProto) bool {
    return !strings.HasPrefix(file.GetPackage(), "google.protobuf") || !strings.HasSuffix(file.GetName(), "descriptor.proto")
}
```
But I guess that's more of a temporary hack for us. Should there be a whitelist of the `.proto` files in `google.protobuf` that are easy to compile and include (Empty, Timestamp)?

**Comment by awalterschulze** [comment]
gogoprotobuf does not have support for the new proto3 google.protobuf types, yet.

This is part of this issue:
https://github.com/gogo/protobuf/issues/57
I am waiting to see what golang/protobuf does first.

So I would recommend the temporary hack for now.
I am going to close this, since I think I should fix this with 57.
I hope that this acceptable.

**Comment by kixelated** [comment]
Hey @awalterschulze, I was going to make a new issue but it makes sense to reopen this one.

We'd like to switch to gogo because our application spends most of its time marshalling/unmarshalling. There's a lot of legacy code involved so we'd just like to use `gofast` to generate backwards-compatible code. Unfortunately, `gofast` does not support the google types. I think it can be generalized that any .proto import will fail if the package was not also compiled with a gogo's marshaller.

We would love to use the `stdtime` extension and generate nicer structs, but it's less of an option given the number of projects that import our package. We also can't use the gogo ptypes package because the existing code expects a `github.com/golang/protobuf/ptypes/timestamp.Timestamp`. We'll probably end up using the extensions in the future, but it's much easier to sell gofast as a drop-in replacement.

The core of the issue is that gogo blindly expects every message to implement `Size()`, `Marshal()` and `Unmarshal()`. I've taken a quick look and I think places [like this](https://github.com/gogo/protobuf/blob/f6b4bb7b2dde1736b809b3da996ed72f278e9be9/plugin/marshalto/marshalto.go#L987) could fall back to something like `proto.Size(accessor)`. It uses reflection so it'll be slower than ideal, but at least there's the option to be backwards-compatible.

**Comment by kixelated** [comment]
Here's what we're seeing:

```
syntax = "proto3";

import "google/protobuf/timestamp.proto";

message Request {
	google.protobuf.Timestamp expiration = 1;
}
```

```
// Code generated by protoc-gen-gogo.
// source: test.proto
// DO NOT EDIT!

/*
	Package test is a generated protocol buffer package.

	It is generated from these files:
		test.proto

	It has these top-level messages:
		Request
*/
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Expiration *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=expiration" json:"expiration,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptorTest, []int{0} }

func (m *Request) GetExpiration() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
}
func (m *Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Request) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Expiration != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTest(dAtA, i, uint64(m.Expiration.Size()))
		n1, err := m.Expiration.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func encodeFixed64Test(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Test(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintTest(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Request) Size() (n int) {
	var l int
	_ = l
	if m.Expiration != nil {
		l = m.Expiration.Size()
		n += 1 + l + sovTest(uint64(l))
	}
	return n
}

func sovTest(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTest(x uint64) (n int) {
	return sovTest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTest
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Expiration == nil {
				m.Expiration = &google_protobuf.Timestamp{}
			}
			if err := m.Expiration.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTest
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTest
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTest(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTest = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTest   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("test.proto", fileDescriptorTest) }

var fileDescriptorTest = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07,
	0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x20, 0x0a,
	0x94, 0x5c, 0xb9, 0xd8, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xac, 0xb8, 0xb8, 0x52,
	0x2b, 0x0a, 0x32, 0x8b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d,
	0xa4, 0xf4, 0x20, 0x06, 0xe8, 0xc1, 0x0c, 0xd0, 0x0b, 0x81, 0x19, 0x10, 0x84, 0xa4, 0xda, 0x49,
	0xe0, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf1, 0x58,
	0x8e, 0x21, 0x89, 0x0d, 0xac, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x86, 0x95, 0x8c, 0x4e,
	0x8e, 0x00, 0x00, 0x00,
}
```

```
./test.pb.go:71: m.Expiration.Size undefined (type *timestamp.Timestamp has no field or method Size)
./test.pb.go:72: m.Expiration.MarshalTo undefined (type *timestamp.Timestamp has no field or method MarshalTo)
./test.pb.go:112: m.Expiration.Size undefined (type *timestamp.Timestamp has no field or method Size)
./test.pb.go:189: m.Expiration.Unmarshal undefined (type *timestamp.Timestamp has no field or method Unmarshal)
```

**Comment by awalterschulze** [comment]
What type of backwards compatibility are we talking about here?
Because the serialized data will be exactly the same whether you use gofast_out or go_out or gogo_out or gogofast_out or stdtime or etc.

```
github.com/golang/protobuf/ptypes/timestamp.Timestamp
```
And gogoprotobuf timestamp are binary equivalent.
With or without stdtime.

> I think it can be generalized that any .proto import will fail if the package was not also compiled with a gogo's marshaller.

I agree

Is this some type of open source package?

Falling back means that we would first need to check whether a Size method exists as well.
And since the protobuf FileDescriptorSet is not enough to know this, because a user can decide to create their own Size method, we would need to check this at run time.
But we would only need to check this for fields where this is not clear from the protobuf, which should be the minority.

The other problem with fallbacks is that if someone forgot to add marshalers to all their protobufs, they will not get a compile error anymore.  This is a big loose.

What about adding these fallback checks, only for ptypes, when they are not the gogoprotobuf types?  If you are willing to contribute?

**Comment by kixelated** [comment]
It's not an open source project, but a common package at work. I know everything is wire compatible but the resulting struct is not code compatible. I would have to submit pull requests for every project that uses this timestamp because the type has changed, even if the functionality has not.

If the user creates their own Size method, would we even want to use it? It seems very specific to the protobuf marshaller/unmarshaller. It seems like things would go horribly wrong and isn't a use-case we need to support.

And yeah, some people won't realize that using the google ptypes is slower. `gofast` should aim for compatibility above all else, but you still want the "faster" compilers. Documentation goes a long way but I was also wondering why `gogofast` doesn't import gogo's ptypes. It's still a non-backwards compatible change, but you won't accidentally use the slow ptypes if for some reason you didn't realize stdtime and stdduration exist. You have to use the `-M` redirect right now to use gogo's ptypes.

I also noticed that stdtime and stdduration just use another function to calculate the size/etc. It starts to bloat the code pretty quickly but you could do the same for ptypes. Otherwise I'll take a look and see what work would have to be done.

**Comment by awalterschulze** [comment]
On Tue, 18 Apr 2017 at 21:22 Luke Curley <notifications@github.com> wrote:

> It's not an open source project, but a common package at work. I know
> everything is wire compatible but the resulting struct is not code
> compatible. I would have to submit pull requests for every project that
> uses this timestamp because the type has changed, even if the functionality
> has not.
>
I assume they lock the version of this common package they are using?
So it sounds painful, but doable.

> If the user creates their own Size method, would we even want to use it?
> It seems very specific to the protobuf marshaller/unmarshaller. It seems
> like things would go horribly wrong and isn't a use-case we need to support.
>
Size might be a bad example, but it is possible to write more efficient
versions of MarshalTo and Unmarshal than even gogoprotobuf can come up with.
I have personally done this with a team mate and this removed the current
bottleneck in the performance profile.

> And yeah, some people won't realize that using the google ptypes is
> slower. gofast should aim for compatibility above all else, but you still
> want the "faster" compilers. Documentation goes a long way but I was also
> wondering why gogofast doesn't import gogo's ptypes. It's still a
> non-backwards compatible change, but you won't accidentally use the slow
> ptypes if for some reason you didn't realize stdtime and stdduration exist.
> You have to use the -M redirect right now to use gogo's ptypes.
>
I have not implemented support for ptypes in gofast, but I would welcome
such a pull request.

Even golang/protobuf using the -M redirect for its ptypes
https://github.com/golang/protobuf/blob/master/proto/Makefile#L42

I also find it inconvenient, but I couldn't find a way around it.

> I also noticed that stdtime and stdduration just use another function to
> calculate the size/etc. It starts to bloat the code pretty quickly but you
> could do the same for ptypes. Otherwise I'll take a look and see what work
> would have to be done.
>
I think once you start using stdtime and stdduration you are in extensions
land and gofast is no longer going to cut it.

**Comment by kixelated** [comment]
If you turn off the sizer but not the marshaller then yeah, it would use the slow `proto.Size(message)` instead of throwing a compilation error. That would make it impossible to write your own fast Size/ProtoSize method but it enables you to import messages not built using gofast (including standard types). I think the compatibility is a huge win.

I personally don't understand when to use gogo/proto (gogofast) versus golang/proto (gofast). A coworker brought up the point that we shouldn't use gogofast because it will use `gogo/proto.RegisterType` while other parts of the non-migrated code will use `golang/proto.RegisterType`. It doesn't seem to matter for my simple program that only uses Marshal/Unmarshal but maybe you could provide some insight. Some extensions obviously work with google's package (marshaller/sizer/unmarshaller), how do I determine if other extensions like stdtime and stdduration would also work?

**Comment by awalterschulze** [comment]
gofast is just going to work for generating marshalers, unmarshalers and size methods.
It is very limited but an easy first step.
It does not work for extensions and doesn't work for any other customization, for example stdduration, stdtime, etc.
Also as you pointed out it does not work for ptypes at all.  Although I think ptypes might be solvable for most ptypes, maybe not all.  This does require some development work though.

gogofast, gogo, etc can be used for all other cases.
gogofast, just enables some extensions by default like marshalers, unmarshalers, etc.
gogofaster, enables more
gogoslick, enables even more
It also shows that you can easily build your own vanity binary as many users have done.

You can use the `goproto_registration` extension to make sure that you still register to golang/proto as well as gogo/proto.  This is especially useful when integrating with grpc-gateway.

**Comment by kixelated** [comment]
@awalterschulze I'm trying out some stuff. The idea is that for a given message, I will use `Size` if the sizer extension is enabled and/or `MarshalTo` if the marshaler or unsafe_marshaller extensions are enabled. Maybe this can be gated behind a compatibility extension to avoid accidentally using the slow `proto.Marshal` and friends.

For a given field, I can check the `FieldDescriptorProto` to see if any of these extensions are enabled. Unfortunately, I also need to get the `FileDescriptorProto` for the corresponding field type because of the _all extensions.

It's pretty crude but I have:
```
obj := p.ObjectNamed(field.GetTypeName()).(*generator.Descriptor)

marshaller := gogoproto.IsMarshaler(obj.File(), obj.DescriptorProto) || gogoproto.IsUnsafeMarshaler(obj.File(), obj.DescriptorProto)
sizer := gogoproto.IsSizer(obj.File(), obj.DescriptorProto)
protoSizer := gogoproto.IsProtoSizer(obj.File(), obj.DescriptorProto)
```

It almost works but it doesn't work for `gogo/types/Timestamp` (and probably others). The `FileDescriptorProto` does not contain any gogo extensions like I would expect. I can inspect `Options` and see things like `go_package:"types"`. Am I on the right track? Is there some sort of special processing required to recognize gogo extensions?

**Comment by awalterschulze** [comment]
This looks like the right track, but you will need to do a new creative
check for timestamp and other ptypes.

**Comment by kixelated** [comment]
What is special about Timestamp and friends? I just assumed they were normal messages just stored in the proto repo.

The blocker for us switching to gogo right now is the inability to import proto files in other repos not using gogo. That's why I'm trying to make sure any generic message can work with the marshaller and want to avoid special-casing the ptypes.

**Comment by awalterschulze** [comment]
Well to get proper marshaling speed that is expected by gofast you'll have
to generate the marshaling code for timestamp for each file where it is
used.

So you'll have to specifically check that it is one of the golang protobuf
ptypes. Maybe this is already done somewhere in the proto package. I would
go and find it for you, but I am going on holiday right now.

**Comment by awalterschulze** [comment]
Generated code is one thing, but the real speed gain from gogoprotobuf is
using the structs you actually want to use. This requires some
customization and is where the other extensions that you cant use with
gofast comes in. I am trying to say that the effort spent in trying to get
gofast to work might be better spent going to gogo. Then you can also get
the stdtime and stdduration that you wanted in the first place.

**Comment by lyw0149** [comment]
> Hello,
> 
> This issue seems still valid, I have the error described in the opener. Also it was said to be resolved with support of proto3 but the issue for proto3 is closed now.
> 
> I want to use google.protobuf.Timestamp and this issue is the only thing keeping me away from gogo protobuf. Is it possible to reopen this issue ?

please try below:
google.protobuf.Timestamp timestamp = 4  [(gogoproto.stdtime) = true];
