### ISSUE TITLE
Has anyone successfully used or figured out a solution for grpc-gateway?

### ISSUE THREAD

**Issue by peter-edge** [gogo/protobuf#138]
I did this https://github.com/peter-edge/grpc-gateway-gogo which is basically an automated fork of grpc-gateway, but thought someone else might have done this before.

**Comment by awalterschulze** [comment]
Sorry I have been sick, but are you sure you can't use grpc-gateway with a grpc service that is generated with gogoprotobuf.   I should think its possible, since grpc-gateway is only a gateway.  I guess that your fork is quite useful if you only want to import one of the golang protobuf libraries.  Is that the usecase of what was the usecase you had in mind?

**Comment by peter-edge** [comment]
No I am not sure, and I'm going to verify it does not work, see https://github.com/gogo/protobuf/issues/137 on global registration issues (which is especially important with grpc-gateway https://github.com/gengo/grpc-gateway/blob/master/third_party/googleapis/google/api/annotations.pb.go#L41)

**Comment by awalterschulze** [comment]
Ok I'll be waiting to here from you.

**Comment by peter-edge** [comment]
Good news, I have confirmed it just works, no register issues :)

https://github.com/peter-edge/openflights-go/compare/gogo?expand=1

Sorry for the bother.
