### ISSUE TITLE
customtype: no encoder for custom.Uint128

### ISSUE THREAD

**Issue by dghubble** [gogo/protobuf#166]
I've been trying out `customtype` and can't get it to work with the custom.Uint128 or any of my own types either.

Take a working proto3 message type and add a `customtype`.

    syntax = "proto3";
    package storagepb;
    import "github.com/gogo/protobuf/gogoproto/gogo.proto";
    type MyMessage struct {
          ...
          bytes right = 6 [(gogoproto.customtype) = "github.com/gogo/protobuf/test/custom.Uint128"];
    }

Generation with `protoc --gogo_out=plugins=grpc:. -I=my/paths *.proto`

    import _ "github.com/gogo/protobuf/gogoproto"
    import github_com_gogo_protobuf_test_custom "github.com/gogo/protobuf/test/custom"
    type MyMessage struct {
         ...
         Right    *github_com_gogo_protobuf_test_custom.Uint128 `protobuf:"bytes,6,opt,name=right,proto3,customtype=github.com/gogo/protobuf/test/custom.Uint128" json:"right,omitempty"`
    }

Now whenever this message is sent across the wire, I get log output

    proto: no encoder function for *custom.Uint128 -> custom.Uint128
    proto: no encoder for Right *custom.Uint128 [GetProperties]

Same issue with or without nullable.

I haven't used this library before so maybe I'm doing something basic wrong, but the cause is opaque to me. I'm testing the Uint128 here (instead of my own type) to ensure I haven't done the JSON `Marshal` and `Unmarshal` incorrectly. The generated `.pb.go` file contains no generated Marhsal or Unmarshal methods. How is this supposed to work? What's the support status with proto3 and customtype?

I see the tests use `protoc-gen-combo` (missing docs?) but haven't been able to get that to work either. Why is it invoked that way?

**Comment by awalterschulze** [comment]
protoc-gen-combo is only really useful for tests.  It generates a bunch of folders for each combination of marshalers and unmarshalers, true and false.

It sounds like its supposed to work.
I do have a test for exactly this situation in test/theproto3/theproto3.proto
```
message Uint128Pair {
  bytes left = 1 [(gogoproto.nullable) = false, (gogoproto.customtype) = "github.com/gogo/protobuf/test/custom.Uint128"];
  bytes right = 2 [(gogoproto.customtype) = "github.com/gogo/protobuf/test/custom.Uint128"];
}
```
So I think I must be missing something.

Are you using the github.com/gogo/protobuf/proto library to Marshal instead of the github.com/golang/protobuf/proto library?

Marshalers and Unmarshalers are only generated if they are specifically turned on.
```
import "github.com/gogo/protobuf/gogoproto/gogo.proto";
option (gogoproto.unmarshaler_all) = false;
option (gogoproto.marshaler_all) = false;
option (gogoproto.sizer_all) = true;
```
Or you could use the protco-gen-gogofast binary. 
```
protoc --gogofast_out=plugins=grpc:. -I=my/paths *.proto
```

But again everything should work even though you haven't turned on marshalers.  It should just be slower.

Are you maybe trying to use it on appengine?

**Comment by dghubble** [comment]
I'm not on appengine, not using any options, and not importing anything to Marshal since the custom.Uint128 is imported from gogo protobuf and should handle marshaling I believe.

If I get some time, I'll put an example repo up to reproduce.

**Comment by awalterschulze** [comment]
You should be importing gogo.proto
```
import "github.com/gogo/protobuf/gogoproto/gogo.proto";
```
But protoc should give a compile error if you don't.

This is very weird.

**Comment by dghubble** [comment]
I ended up using the regular standard protobuf generator and converting between structs instead of this. Closing.

**Comment by awalterschulze** [comment]
That is not really helping me to solve the issue :( but fair enough.

**Comment by abursavich** [comment]
I came across this old issue when hitting something similar with a `gogoproto.stdtime` field and [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway). It was a frustrating problem to solve, so for the benefit of anyone else who may hit it in the future:

I ended up extracting the [runtime.JSONPb](https://godoc.org/github.com/grpc-ecosystem/grpc-gateway/runtime#JSONPb) code, changing the `jsonpb` and `proto` imports to the `gogo` versions, and then setting it as a custom Marshaler on the `runtime.ServeMux`.

```go
mux := runtime.NewServeMux(runtime.WithMarshalerOption(runtime.MIMEWildcard, &gogomarshal.JSONPb{}))
```

Here's my `gogomarshal` package which is 99.9% lifted from the `github.com/grpc-ecosystem/grpc-gateway/runtime` package: https://gist.github.com/abursavich/d8cae1b0dee39cb17e05095e088d113f

**Comment by johanbrandhorst** [comment]
@abursavich note that this kind of solution has been discussed before, going back to https://github.com/gogo/protobuf/issues/178. CockroachDB provided a similar solution to yours. I've written more about this an other gogo compatibility issues with the gRPC-Gateway in a post on my blog: https://jbrandhorst.com/post/gogoproto/.

**Comment by awalterschulze** [comment]
Thank you very much both of you :)

@abursavich How do you use the `Proto` type that you have also included in https://github.com/abursavich/gogomarshal ?

**Comment by awalterschulze** [comment]
@tamird What do you think about https://github.com/abursavich/gogomarshal
when compared to the cockroachdb solution?

**Comment by tamird** [comment]
@awalterschulze looks the same with a few minor differences:
- CockroachDB uses a different content type: `application/x-protobuf` rather than `application/octet-stream`
- @abursavich's code better handles decoding non-protos - CockroachDB simply refuses to do so: https://github.com/cockroachdb/cockroach/blob/0de6b0ea9acbb8c2f1faa0be9014436035e1653b/pkg/util/protoutil/jsonpb_marshal.go#L120 -- note that CRDB still supports *en*coding non proto fields which is needed for grpc-gateway to be able to emit errors.

Other than that, the two are identical AFAICT.

**Comment by awalterschulze** [comment]
Maybe we can standardize this marshaler and unmarshaler into a github.com/gogo repo, because this something many people use these days.
What do you think?

**Comment by tamird** [comment]
@awalterschulze seems fine to me. I don't think there's any reason to include a proto marshaler (i.e. https://github.com/abursavich/gogomarshal/blob/master/protopb.go) since upstream's is just fine (and was added in (https://github.com/grpc-ecosystem/grpc-gateway/pull/459). We would switch to that as well, but it has the wrong content type for us. The important part is to use `gogo/protobuf.jsonpb`.

**Comment by abursavich** [comment]
I'm new to both gogoproto and grpc-gateway. I'm happy to contribute code and it would be nice to have it in github.com/gogo, but I'm not certain that I should be the owner as I'm still ramping up at the moment. If you want to adopt my package, I agree that the naming should be changed but I don't have any good suggestions yet.

I would caution that grpc-gateway's [ProtoMarshaler](https://github.com/grpc-ecosystem/grpc-gateway/blob/039532580f67bea4448ba779550b8d0d1614db95/runtime/marshal_proto.go#L7) uses `github.com/golang/protobuf/proto`, while cockroachdb's and mine use `github.com/gogo/protobuf/proto`. I went ahead and slapped a [CustomContentType](https://github.com/abursavich/gogomarshal/blob/974527c20aaa00da2f5045a017b4b7665618c4f9/proto.go#L17) field on mine to allow `application/x-protobuf`.

**Comment by awalterschulze** [comment]
@abursavich  @tamird  @johanbrandhorst  ^^

**Comment by johanbrandhorst** [comment]
Sounds good to me :)

**Comment by awalterschulze** [comment]
Are you also volunteering? :)

**Comment by abursavich** [comment]
I'll volunteer.

**Comment by awalterschulze** [comment]
Cool I made you admin of github.com/gogo/gateway
Please let me know if you haven't received an invite

**Comment by awalterschulze** [comment]
@abursavich No rush. I just want to make sure.  Did you receive the invite to the repo?

**Comment by abursavich** [comment]
Yes, I did. I have a new version of the code ready, but I'm waiting to find out about a licensing issue before pushing it.

**Comment by awalterschulze** [comment]
Cool. You are welcome to add any bsd, apache, MIT type license with any
copyright. This is just a url.

**Comment by awalterschulze** [comment]
@abursavich no rush, just checking in.  Have you had any luck yet?
