### ISSUE TITLE
change to SupportPackageIsVersion3 for gRPC

### ISSUE THREAD

**Issue by gyuho** [gogo/protobuf#185]
Could we change https://github.com/gogo/protobuf/blob/master/plugin/grpc/grpc.go#L51 to version 3?

Now it's `SupportPackageIsVersion3` in gRPC.

Related:

- https://github.com/grpc/grpc-go/commit/e78224b060cf3215247b7be455f80ea22e469b66
- https://github.com/coreos/etcd/issues/5671

Please feel free to close this if I am asking the wrong question.

Thanks!

**Comment by dongsupark** [comment]
+1.
I just stumbled across this issue, while building torus, which depends on etcd, which depends again on grpc. As a workaround, I had to manually revert https://github.com/grpc/grpc-go/commit/e78224b060cf3215247b7be455f80ea22e469b66 to get the build working.

**Comment by ax-nathan** [comment]
+1

**Comment by beejeebus** [comment]
i created #187 to fix this issue.

**Comment by awalterschulze** [comment]
Sorry for the delay
You are talking about merging this commit
https://github.com/golang/protobuf/commit/0c1f6d65b5a189c2250d10e71a5506f06f9fa0a0
which requires this commit
https://github.com/golang/protobuf/commit/545732fb9671625a62a399186a066c4f8b942bc5

**Comment by awalterschulze** [comment]
The file index concept in golang/protobuf to avoid variable name conflicts is fundamentally flawed.  gogoprotobuf rather uses the filename as a suffix to its generated variables to avoid many more conflicts.

For example:

Running these two in the same folder

protoc --gogo_out=. a.proto
protoc --gogo_out=. b.proto

will produce two variables with the same index value (0) and thus same name in the same package which will result in a go compiler error.

So whether to merge this is an interesting question.

Clearly they incremented the version number because they added a populated field which changes the API semantics.  So this needs to be taken seriously.

**Comment by awalterschulze** [comment]
@tamird can you remember where we or someone logged this issue?  I want to link it again.

**Comment by awalterschulze** [comment]
Ok so it just links to the generated fileDescriptor.  This should be easy to merge.

**Comment by awalterschulze** [comment]
Done https://github.com/gogo/protobuf/commit/55bbb6b06500583c00622bed89473ed1fcd06e2f

**Comment by awalterschulze** [comment]
@tamird please ignore my request.

**Comment by gyuho** [comment]
Thanks a lot!
