### ISSUE TITLE
Plugin for registering messages with golang/protobuf

### ISSUE THREAD

**Issue by johanbrandhorst** [gogo/protobuf#269]
As mentioned in #178, this is necessary if using the grpc-gateway and expect it to work with things like enum value mappings and JSON marshalling using the default marshaler.

**Comment by awalterschulze** [comment]
The proposal is to make an extension that registers messages and enums with both gogoprotobuf and golang/protobuf.
Do we think that is all that is needed?
Is there someone who wants to make this feature?

**Comment by johanbrandhorst** [comment]
@awalterschulze I've confirmed that the issue I mentioned in #178 is fixed by registering all messages and enums with both gogoprotobuf and golang/protobuf. Currently we're doing it with the sed magic strings provided by mwitkow.

**Comment by awalterschulze** [comment]
Thats good to know :)
Are you interested in implementing this feature?

**Comment by johanbrandhorst** [comment]
I could take a stab at it, I've just got no idea how to make a new plugin and how it would interact with the other plugins and registration. Would it just mean writing a plugin that adds registration for `golang/protobuf` or would I need it to do any other magic?

**Comment by awalterschulze** [comment]
1) Well first we need to define a new extension in 
https://github.com/gogo/protobuf/blob/master/gogoproto/gogo.proto
We need to come up with a name for our boolean extension.
This we could do here in the issue.

2) I don't think this requires a totally new plugin, since its such a small change, we could add this inside generator.go
Here is are some of the locations that will require some work
The Register locations:
  - https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/generator/generator.go#L3037
  - https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/generator/generator.go#L3095
  - https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/generator/generator.go#L3145
  - https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/generator/generator.go#L3177
  - https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/generator/generator.go#L3181

And then this is the other plugin with which it might interfere
https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/generator/generator.go#L1418-L1422

**Comment by johanbrandhorst** [comment]
@awalterschulze that's extremely helpful, thanks! What is the convention for naming plugins? Would `std_registration` or `golang_registration` be suitable?

**Comment by awalterschulze** [comment]
Good question :)
The only convention sofar is the _all convention, but this is not applicable in this case.
Naming is hard.
What do you think about `double_registration`?
The name should try is hardest to describe the behavior.  So that the documentation is almost unnecessary. 
I want to say `additional_golang_registration`, but thats too long.

**Comment by awalterschulze** [comment]
I also don't think that double_registration is really helping the user understand what it does :(

**Comment by awalterschulze** [comment]
Another convention is to use the `goproto` prefix when it has something to do with traditional golang/protobuf, because it was originally code.google.com/p/goprotobuf vs code.google.com/p/gogoprotobuf.

**Comment by johanbrandhorst** [comment]
Indeed, I guess what the plugin is used for is for compatibility with third party libraries using golang/protobuf, maybe `std_import_compat`?

**Comment by johanbrandhorst** [comment]
`goproto_import_compat`?

**Comment by awalterschulze** [comment]
I would prefer to reserve `std` for implying something about the golang standard library.
`goproto_import_compat` is better, but then its still a bit confusing in light of `gogoproto_import`.  Maybe we should leave the word import out of it?

**Comment by awalterschulze** [comment]
And then we can't use the word `compat` because we are not really compatible with golang/protobuf, because of things like nullable=false, customtype, etc.

**Comment by awalterschulze** [comment]
I think you first suggestion was the best, but I'll modify it a bit for convention
`goproto_registration`
What do you think?

**Comment by johanbrandhorst** [comment]
Sounds like it's decided :+1:. I'll take a look at this sometime today.

**Comment by johanbrandhorst** [comment]
I did a first pass of it, no tests yet, let me know your thoughts https://github.com/gogo/protobuf/pull/270

**Comment by oguzyildiz1991** [comment]
This is lifesaver, thanks!

**Comment by johanbrandhorst** [comment]
@oguzyildiz1991 I covered this and other tips in https://jbrandhorst.com/post/gogoproto/, in case you hadn't seen it already.

**Comment by oguzyildiz1991** [comment]
Thanks! I'll read that today

**Comment by oguzyildiz1991** [comment]
This has helped with the enums, but unfortunately didn't help with oneof fields. 
Using gogo's jsonpb works, but we have such a big codebase, I need a solution that would make golang's jsonpb work as well. 
This is the same issue I'm having https://github.com/gogo/protobuf/issues/548
