### ISSUE TITLE
Grpc-gateway and customname

### ISSUE THREAD

**Issue by rvolosatovs** [gogo/protobuf#331]
When using the `customname` option, generated `grpc-gateway` code still uses the "default" variable name and generated variable names need to be changed manualy. What could be a good way around this?
For now I made a script
```bash
#!/usr/bin/env bash
set -e

function usage {
  echo "Usage: `basename $0` <proto-dir>"
  exit 1
}
[[ ${1} = "" ]] && usage
protoDir=${1}

# TODO figure out a way to traverse only files imported by protos using grpc-gateway(google.api.http option)
protos=(${protoDir}/*.proto)
genFiles=()

IFS_BAK=${IFS}
IFS="
"

sedArgs=()
for f in ${protos[@]}; do
  grep -q '(google.api.http)' ${f} && genFiles+=(${f%".proto"}".pb.gw.go")
  grep -q '(gogoproto.customname)' ${f} && lines=(`cat ${f} | grep '(gogoproto.customname)'`) || continue

  for l in ${lines[@]}; do
    from=`echo $l | sed 's/[ ]*\(repeated[ ]\+\)\?[[:alnum:]_.]\+[ ]\+\([[:alnum:]_]\+\)[ ]*=[ ]*[0-9]\+.*/\2/' | sed 's/_\([a-z]\)/\u\1/g' | tr -d ' ' | sed 's/\(^[:a-z:]\)\(.*\)/\u\1\2/' | tr -d '_' `
    to=`echo $l | sed 's/.*(gogoproto.customname)[  ]*=[ ]*"\([[:alnum:]]\+\)".*/\1/' | tr -d ' '`
    sedArgs+=("-e s/\([^[:alnum:]]\)${from}\([^[:alnum:]]\)/\1${to}\2/")
  done
done
IFS=${IFS_BAK}

sed -i ${sedArgs[*]} ${genFiles[*]}
exit 0

```
which seems to work. Any thoughts on how this can be done better?

**Comment by awalterschulze** [comment]
grpc-gateway is a separate project from gogoprotobuf.
grpc-gateway is probably not going to care about gogoproto.customname and gogoprotobuf cannot change the code generated by grpc-gateway.
So you are in a bit of pickle.
I would try to understand if you really need customname and cannot just rename your fields/messages.
Next you could try forking grpc-gateway and make your fork know about customname and that way you can make sure that you generate the correct code in the first place, but you will probably need to maintain the fork then.
Or you could even write a go/ast walker that updates the generate grpc-gateway code rather than using grep, but all these choices have their trade offs.
Sorry.

**Comment by rvolosatovs** [comment]
Yeah, that's pretty much what I thought.
Probably will look into a more robust solution with `go/ast` later.
Thanks for the fast and extensive reply!

**Comment by awalterschulze** [comment]
Sorry for the situation :(
