### ISSUE TITLE
generating protobufs against google/rpc (googleapis et al)

### ISSUE THREAD

**Issue by stevvooe** [gogo/protobuf#340]
There are few problems in integrating with protobufs exported from googleapi. Check out https://github.com/googleapis/googleapis/tree/master/google/rpc for an example. The problem is that the protobuf file and the genproto files are in different projects.

I have a hack working with [protobuild](github.com/stevvooe/protobuild) but I have to bring in the external protobufs and modify them to all be in a single package for it to work. I can make this available (its on containerd) once I submit the PR.

Let me know what the story is here and how I can help. There are definitely a few options.

**Comment by awalterschulze** [comment]
Maybe you can show me a build error or I am tired, but I am struggling to understand the problem?

**Comment by stevvooe** [comment]
@awalterschulze I've lost the build errors, but here is the PR: https://github.com/containerd/containerd/pull/1597.

1. I had to find a place to import the protobufs. I ended up bringing them into the project.
2. I had to find Go project with the correctly built types.

However, when achieving 2, I ended up with the standard missing Size and MarshalTo error when integrating gogo and standard protobufs.

I ended up having to bring the definitions into the project and mapping the import root to the containerd path. Ideally, gogo would make these available in a single dependency (maybe), but I am not sure what the suggested best practice for using these would be.

**Comment by awalterschulze** [comment]
I brought in all the proto files from https://github.com/google/protobuf/tree/master/src/google/protobuf to get a sane build.
This was also the only way I could get it working.

> I really struggle to keep this project compatible with grpc and most of it is not grpc's fault.
The way that the codec interface is designed does not allow for optimal performance.
Other than that in golang/protobuf the jsonpb library and the registration of protos are really killing me with grpc gateway.
And then there is also the locations of the protos and how this struggles to play along with gopaths.
Before grpc and jsonpb this was all much simpler.
rant complete.

Since I am not currently using grpc or protobufs :( I am going to really on suggestions for how to help.  Sorry, I wish I knew how to fix this.

**Comment by stevvooe** [comment]
Perhaps, you can carry them in the https://github.com/gogo/protobuf/tree/master/protobuf tree, for use by other projects. The solution we have for containerd will work for us, though.

> Since I am not currently using grpc or protobufs

:( Are you still maintaining this project? Do you need help?

**Comment by awalterschulze** [comment]
Carry the grpc protos in the protobuf library?

Don't worry I am still maintaining the library. I have not been using
protobufs for a year now, but I am still maintaining gogoprotobuf. I
sometimes even think if I can still do this differently. Also one of the
new issues will hopefully result in a small performance improvement. But I
am not thinking of new features. For this I rely on contributors.

**Comment by awalterschulze** [comment]
Also if you have too much time, then I have labeled the issues I need help on with `help wanted`.

**Comment by stevvooe** [comment]
> Also if you have too much time

:eyes:

**Comment by awalterschulze** [comment]
I have finally created https://github.com/gogo/googleapis
If you want more protos in there, pull requests and maintainers are welcome.
I think it solves this issue.

**Comment by stevvooe** [comment]
@awalterschulze That might work. I think we ended up doing a lot of inline generation for these.

**Comment by stevvooe** [comment]
Let me know if you need a maintainer there.

**Comment by awalterschulze** [comment]
@stevvooe Always :)
Thank you so much. I'll add you as a maintainer.

**Comment by awalterschulze** [comment]
Could you provide an example of inline generation?

**Comment by stevvooe** [comment]
@awalterschulze I just regenerated them in the project directly: https://github.com/containerd/containerd/tree/master/protobuf/google/rpc.

**Comment by awalterschulze** [comment]
Aha so very similar to what gogo/googleapis is now, except it is local to
your project.

**Comment by awalterschulze** [comment]
Gogo/googleapis just added XXX_MessageName to help with grpc gateway
compatibility. See the gogo/grpc-example repo where Johan is tackling all
the grpc compatibility issues.

**Comment by stevvooe** [comment]
@awalterschulze Not sure if you had a peak at https://github.com/stevvooe/protobuild, but that may also help. It makes it very easy to switch imports.

**Comment by awalterschulze** [comment]
No, since I am a bit out of the protobuf loop at the moment, because I
don't get to use them at work :(

I think protoeasy tried something similar, but since I am not a user I
never get to try it out.

Am I understanding correctly that this allows you to only set your -M
parameters once? Or is there more?

Is it helping containerd have more manageable builds?

I wish I was a user :(
