### ISSUE TITLE
Start doing binary releases with GitHub releases

### ISSUE THREAD

**Issue by peter-edge** [gogo/protobuf#366]
I want to be able to curl ie `gogo-protobuf-Darwin-x86_64.tar.gz` that contains all the binaries such as `protoc-gen-gogo`, `protoc-gen-gogoslick`, etc. You build them in a Docker container first. I have some experience with this if you are ok with it.

**Comment by awalterschulze** [comment]
I am sorry, but I don't think I want to maintain this. For each gogoprotobuf release there should already a debian release that is being maintained by them.

**Comment by awalterschulze** [comment]
I also don't see how it would work, since you still need the library as well.  And then you might end up with different binary and library versions.  If this was only a binary then I would consider this, if there was also a travis like service that I could use to build these binaries for me, for each platform including windows.
