### ISSUE TITLE
before merging dev

### ISSUE THREAD

**Issue by awalterschulze** [gogo/protobuf#413]
Most of the work has been done.
We are really close to merging the dev branch into master:

  1. We need to merge the swaptypeassert branch.  @jmarais and @donaldgraham are working on this and are close to solution.
  2. We need to decide whether we want to add an option to not generate the new XXX_sizecache and XXX_Unkeyed... fields.  These new fields create incompatibilities for some users who are using generated messages as map keys or copying values with a single assignment statement.  This might be a restricted enough use case to not do anything, but I would like to pause for a moment before rushing into this decision either way.

So let's discuss number 2

@johanbrandhorst , @tamird

**Comment by johanbrandhorst** [comment]
Even if we added an option not to generate the new fields, we would have to turn on the new fields by default, right? Either way this will be a backwards incompatible change for those users (either because they have to enable this option and regenerate or because they upgrade and find their use case is no longer supported). I'd argue in favor of not having an option until we find there's enough demand for one.

**Comment by awalterschulze** [comment]
Cool.  Good point.
I was thinking that if we had the option, then would at least be quick for them to fix their code.
But this is great feedback and exactly what I was looking for :)

**Comment by awalterschulze** [comment]
@jmarais and @donaldgraham have completed number one and also fixed a bug with deterministic marshaling in golang/protobuf

We are now ready to merge dev https://github.com/gogo/protobuf/pull/424/files

It seems that everyone is happy with point 2 being fixed when it becomes a problem, so I am going to close this issue.
