### ISSUE TITLE
What's the different between unsafe_marshaler and general marshaler

### ISSUE THREAD

**Issue by chenttuuvv** [gogo/protobuf#43]
@awalterschulze  I have diff against the pb.go file generated by the protoc compiler, with unsafe option turn on and off, but they look exactly the same. Can you highligh some pro and cons of using unsafe_marshaler.

thanks

**Comment by awalterschulze** [comment]
Are you using any of double, float, fixed64, fixed32, sfixed64, sfixed32?
These are the only types that really benefit from unsafe at the moment.
Most of the time they are the same.
I thought it might be important to sometimes be able to not use any unsafe imports such as in the case of appengine, which I don't fully support anyway.
Now I have a fallback for when go does backwards incompatible stuff with unsafe, which they have not promised not to do.
We use unsafe internally, but both are very well tested, in my opinion.
I hope this has answered your question, otherwise feel free to comment again.
