### ISSUE TITLE
enum_camelcase_all flag for idiomatic enum casing?

### ISSUE THREAD

**Issue by leeola** [gogo/protobuf#481]
Idiomatic protobuf dictates that enum values should be declared in all caps. Go says camel case for constants.

With that said, gogoprotobuf allows you to use `[(gogoproto.enumvalue_customname) = "MyBetterNameA"]` to correct this naming inconsistency. However this requires you use it on every single enum value in your proto file. This can become cumbersome.

An option like `option (gogoproto.enum_camelcase_all) = true;` would ease this issue.

Thoughts?

**Comment by jmarais** [comment]
Hey, Sorry for the late reply.

It is a good suggestion. However:
https://github.com/golang/go/wiki/CodeReviewComments#initialisms
Suggests that:

> Words in names that are initialisms or acronyms (e.g. "URL" or "NATO") have a consistent case. For example, "URL" should appear as "URL" or "url" (as in "urlPony", or "URLPony"), never as "Url". As an example: ServeHTTP not ServeHttp. For identifiers with multiple initialized "words", use for example "xmlHTTPRequest" or "XMLHTTPRequest".
This rule also applies to "ID" when it is short for "identifier", so write "appID" instead of "appId".

So it might not be as easy to just capitalise the first letter of each word.

However, this could be an example where one can create a vanity binary.
Simple copy gogofaster/main.go
https://github.com/gogo/protobuf/blob/master/protoc-gen-gogofaster/main.go
And modify it with your own customizations.
If you go install it before running protoc then protoc will find protoc-gen-leeola in the $PATH and then you can run ```protoc --leeola_out```

For example containerd added a vanity function to their vanity binary that adds a customname to each id field.
https://github.com/YaoZengzeng/comments/blob/master/containerd/cmd/protoc-gen-gogoctrd/main.go#L22

**Comment by leeola** [comment]
Yea, the suggestion for camelcase_all would definitely not be bulletproof. I suggested it because right now it's wrong 100% of the time, where as if you were using `camelcase_all` then it would only be wrong part of the time. If a user ended up having mostly pure abbreviated names, then they'd simply not use camelcase. In the worst case if they had 50/50 camel/abbrev, half of their enum-values would contain rename options, which is still a reduction by 50%.

Nice note about the vanity, I'll look into it, thanks! I've got a few issues I wanted to bring up about Go naming convention conflicts with Protobuf, and worst case scenario if features don't get implemented/approved I can look into custom vanity builds. Though I imagine idiomatic Go is useful to everyone here, but perhaps I'm just obsessive haha :)

**Comment by jmarais** [comment]
> Though I imagine idiomatic Go is useful to everyone here
Yeh, we currently still have a case open regarding golint compatible generated code:
https://github.com/gogo/protobuf/issues/149

> Nice note about the vanity, I'll look into it, thanks! 
Cool. Good luck.

**Comment by leeola** [comment]
If this _(and my future naming convention issues haha)_ are being tracked in #149, I'll close this and keep it to that issue. Thanks!
