### ISSUE TITLE
nullable, optional fields and has_

### ISSUE THREAD

**Issue by mkevac** [gogo/protobuf#49]
When setting `nullable = false` for a field, we can't say whether optional field is set or not. But we could generate additional field `has_<field_name> bool` that says whether field is set or not.

**Comment by awalterschulze** [comment]
Yes that is true.
nullable = false is not for you if you need to know if the field was set of not.
I tend to not use nullable=false for those respective fields.
having a has_fieldname bool for each field, would also require a setter api, which is not very goey.
You could look at https://github.com/dropbox/goprotoc I know they have a setter api.
Also note that proto3 does not allow you to see if a field has been set of not.  They recommend declaring another bool flag field for each of those "optional" fields.
I hope some of this helps, otherwise please reopen the issue.

**Comment by mkevac** [comment]
Well, nullable = true is not for Go, because GC.
proto3 is very different protocol and I don't think we at Badoo will move to it. We will probably stick to proto2 for a time being.

But I understand your reluctance for adding setters.

**Comment by awalterschulze** [comment]
Do you think you would like to use setters?
Because then there is at least two usecases.
