### ISSUE TITLE
what is the use of this skip function

### ISSUE THREAD

**Issue by newyear6565** [gogo/protobuf#550]
I saw the code in unmarshal.go below:
p.P(`func skip` + p.localName + `(dAtA []byte) (n int, err error) {

what is the use of this skip function,Can anyone help me?

**Comment by jmarais** [comment]
Hi. The skip function is generated in order to handle unknown fields in a well-formed protocol buffer message. Here is the explanation from the documentation:
[https://developers.google.com/protocol-buffers/docs/proto3#unknowns](https://developers.google.com/protocol-buffers/docs/proto3#unknowns)
[https://developers.google.com/protocol-buffers/docs/proto#updating](https://developers.google.com/protocol-buffers/docs/proto#updating)

Essentially it means if I have the older .proto definition:
```protobuf
message Foo {
 string Bar = 1;
}
```
and you add a new field:
```protobuf
message Foo {
 string Bar = 1;
 string Baz = 2;
}
```
When you marshal your message you will have a field which I do not understand (```Baz```). So when I unmarshal your message the unmarshaller will just skip (with the ```skip``` function) those bytes but preserve them by adding them to the ```XXX_unrecognized``` field in the golang struct. This means I can successfully unmarshal your message without updating to the new .proto field. 
Now, when I marshal that message again, the marshaller will add the bytes from ```XXX_unrecognized``` to the serialised buffer. So when you unmarshal the message again the ```Baz``` field would still be there.

**Comment by newyear6565** [comment]
thank you very much for your help @jmarais
