### ISSUE TITLE
Question :  Unmarshal function

### ISSUE THREAD

**Issue by newyear6565** [gogo/protobuf#551]
i use gogofaster

 In  "switch fieldNum" part of the generated Unmarshal function, why not directly compare the "wire" variable, instead of splitting into two variables, "fieldNum" and "wireType"?

**the generated code is like that:**

fieldNum := int32(wire >> 3)
wireType := int(wire & 0x7)
if wireType == 4 {
	return fmt.Errorf("proto: Account: wiretype end group for non-group")
}
if fieldNum <= 0 {
	return fmt.Errorf("proto: Account: illegal tag %d (wire type %d)", fieldNum, wire)
}
switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}

**can I change it like this below?**
switch wire {
		case 0xa:
                        deal with field 1
		case 0x12:
                        deal with field 2
                ......

**Comment by jmarais** [comment]
Hey.

I think that is a valid suggestion. I think currently we can supply more specific error messages with the current way of splitting the ```fieldNum``` and ```wireType``` numbers.

We also know that if we fall through to the ```default``` case it is a legitimate addition field that we don't know about and we can preserve. However if we only check for the ```wire``` one could change the type of a field and it wouldn't match and then we would have to do additional checking to see  if it is an invalid type or just an unknown field. example:

```protobuf
message Foo {
 string Bar = 1;
}
```
change to:
```protobuf
message Foo {
 int64 Bar = 1;
}
```
The ```fieldNum``` would stay the same, but the ```wireType``` would change. In this case we can provide the correct error message instead of adding it to the ```XXX_unrecognized``` field.

So one can change it, but you would need additional code in order to distinguish between a real "unknown/new" field vs a "corrupt/wrong" field (in my example).

**Comment by newyear6565** [comment]
Thank you for your answer, now I understand the reasons for this design. @jmarais
